# Generated by Django 3.2.7 on 2021-10-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameName', models.CharField(max_length=200, null=True)),
                ('gameDescription', models.CharField(max_length=1000, null=True)),
                ('gameCode', models.CharField(max_length=100000, null=True)),
                ('gameOwnerUsername', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
