# Generated by Django 3.2.7 on 2021-10-24 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='NewsClass',
        ),
    ]
