# Generated by Django 3.2.7 on 2021-10-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_news_newsclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsclass',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='usergame',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
