# Generated by Django 3.2.7 on 2021-11-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
