# Generated by Django 3.2.7 on 2021-11-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_topiccomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='user_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
